version: '2'
services:
    web:
        image: nginx:alpine
        command: nginx
        restart: always
        ports:
            - 80:80
        volumes:
            - ./www:/usr/share/nginx/www:ro
            - ./staticfiles:/usr/share/nginx/staticfiles:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - sfbdb-vol:/usr/share/nginx/www/sfbdb:ro
    blog:
        build:
            context: ./blog-context
        volumes:
            - ./www/blog:/blog/public

    sfb-database:
        image: postgres:12.3-alpine
        ports:
            - 5431:5431
            - 5432:5432
        env_file:
            - .env
        environment:
            POSTGRES_USER: sfb-ranking-user
            POSTGRES_DB: sfb-ranking
        volumes:
            - sfbranking-db-vol:/var/lib/postgresql/data

    sfb-ranking:
        build:
            context: ./sfb-ranking-context
        ports:
            - "8080:8080"
        command: >
            sh -c "npm run db:migrate -- --env production && NODE_ENV=production npm run server"
        env_file:
            - .env
        volumes:
            - sfbranking-vol:/usr/app/build
        depends_on:
            - sfb-database

    sfb-db:
        build:
            context: ./sfb-db-context
        command: npm run deploy
        volumes:
            - sfbdb-vol:/usr/app/build

volumes:
    sfbdb-vol:
        driver: local
        driver_opts:
            type: none
            device: $PWD/www/sfbdb
            o: bind
    sfbranking-db-vol:
        driver: local
        driver_opts:
            type: none
            device: $PWD/sfb-data
            o: bind
    sfbranking-vol:
        driver: local
        driver_opts:
            type: none
            device: $PWD/www/sfbranking
            o: bind
