version: '3'
services:
    web:
        image: nginx:alpine
        command: nginx
        restart: always
        ports:
            - 80:80
        volumes:
            - ./www:/usr/share/nginx/html:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
    blog:
        build:
            context: ./blog-context
        volumes:
            - ./www/blog:/blog/public
    # blog-admin:
    #     build:
    #         context: ./empty-context
    #         dockerfile: Dockerfile-blog-admin
